camsong/You-Dont-Need-jQuery

README.ko-KR.md

i18n: Support ko-KR (Korean)

---

README.md

Just a suggestion separating `Query by selector` from `Query by id / class`.
Feel free to close if you don't think it's constructive.
Thanks

Update query by class and id

---

README.md

Trim function not have arguments

Fix .trim syntax

---

README.md

Improve the flow of the file. 

---

README-vi.md

Translate to Vietnamese

---

README-id.md

Added Indonesian Language

---

README.pt-BR.md

- Fixed some semantic errors
- Added more portuguese expressions and terms
- Fixed some typos and ponctuation
- Entire table of contents in portuguese (when needed)
- Title of the page in portuguese

Update on pt-br translation

---

README-id.md
README-my.md
README-vi.md
README.ko-KR.md
README.md
README.pt-BR.md
README.zh-CN.md

fix native implementations of [insertBefore](https://github.com/idiotWu/You-Dont-Need-jQuery#3.6) and [insertAfter](https://github.com/idiotWu/You-Dont-Need-jQuery#3.7).

fix: fix native `insertBefore` and `insertAfter`

---

README.md

Adds info about NPM and npm-dom, webmodules organizations.

Add info about NPM 

---

README.md

What about insertAdjacentHTML?
http://www.w3.org/TR/DOM-Parsing/#widl-Element-insertAdjacentHTML-void-DOMString-position-DOMString-text
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
http://caniuse.com/#feat=insertadjacenthtml

Native append and prepend with insertAdjacentHTML

---

README.md

Support ... http://caniuse.com/#feat=matchesselector

jQuery is() filtering

---

README-it.md

I've added an Italian translation of the Readme.
Feel free to include that in the repo if you wish.
Thanks

Italian translation added

---

README-es.md
README-id.md
README-my.md
README-ru.md
README-vi.md
README.md

russian version

---

README.md

Add promise section

---

README.md

Although it's strongly against the recommendation to use these jQuery methods, it will still be nice to have native alternatives for people switching from jQuery,

add `warp()`, `unwrap()` and `replaceWith()` 

---

README.md

add utils description and comparison. fix #31 
and remove xml method related, because xml method are not commonly used.

add other utils method

---

README.md

Add animation section

---

README-es.md
README-fr.md
README-id.md
README-it.md
README-my.md
README-ru.md
README-tr.md
README-vi.md
README.ko-KR.md
README.md
README.zh-CN.md

Full translation in French from README.md.

Add french translation

---

README.md

Utilities:jquery isPlainObject

---

README-fr.md
README.ko-KR.md
README.md

Reference: https://api.jquery.com/jQuery.isNumeric
:octocat:

fix isNumeric references

---

README-es.md
README-fr.md
README-id.md
README-it.md
README-ja.md
README-my.md
README-ru.md
README-tr.md
README-vi.md
README.ko-KR.md
README.md
README.pt-BR.md
README.zh-CN.md

Japanese translation of 1c017f4.

Add Japanese translation

---

README.md

Chrome Version 50.0.2661.86 (64-bit)
IE9 on Win7

fix description of query selector

---

.gitignore
README-es.md
README-fr.md
README-id.md
README-it.md
README-ja.md
README-kg.md
README-my.md
README-ru.md
README-tr.md
README-vi.md
README.ko-KR.md
README.md
README.pt-BR.md
README.zh-CN.md

Added first explanation in Kyrgyz Language

+ Added README-kg.md

---

README-fr.md

Hi,
I've fixed many misspellings in the french version of the repo 👍

Readme-fr.md - Misspelling fixes

---

README.md

fix index error

---

README-es.md

The last version was outdated, so I updated it according to README.md at 4133997

Spanish Translation Updated

---

README.zh-CN.md

fix incorrect url
follow en link style

fix README.zh-CN browser logo

---

README-ru.md

- fix some small misspells 
- edit "machine" translation to native
- correct sentences with wrong meaning
- restore сommon (professional) English words back from Russian.

adopt Russian translation

---

README.md

Can simplify some previous examples ;)

+ Simple parse

---

README.ko-KR.md

fixed indents (line 441 ~ 633)

fixed indents

---

README.zh-CN.md

update function isNumeric for es6 number object

update function isNumeric in README.zh-CN.md

---

README.ko-KR.md

Update ko-KR translation

---

README.md

The example (using {} as first argument) is to create a new object, while the text states that the first object is modified. See:
https://stackoverflow.com/questions/171251/how-can-i-merge-properties-of-two-javascript-objects-dynamically
Also, improved naming.

$.extend()

---

README.md

- Added :contains to selectors
- Fixed some more grammar (in presentation text)
- The code was taken from an answer (and a comment) here: https://stackoverflow.com/questions/17799236/native-javascript-equivalent-of-jquery-contains-selector

Added :contains

---

README.md

Fixes broken formatting in section 8.4.
From ![image](https://user-images.githubusercontent.com/442644/39976738-45e49778-5770-11e8-9b8b-107b41d73b45.png) to

Fix 8.4 formatting

---

README.md

- Added ES-6 way to append/prepend elements
- Made clear that what was called "el" is the parent element, and that jQuery (just like the ES6 method) allows for both DOMString and Node objects in a unified manner.

ES6 append/prepend

---

README.md

syntax highlight

---

README-es.md
README-fr.md
README-id.md
README-it.md
README-ja.md
README-kg.md
README-my.md
README-pl.md
README-ru.md
README-tr.md
README-vi.md
README.ko-KR.md
README.md
README.pt-BR.md
README.zh-CN.md
README.zh-TW.md

add README.zh-TW.md and link of other translation pages

add README.zh-TW.md

---

README.zh-CN.md

$el.remove() can be improved

---

README-ru.md

Added missing sections, minor translation inconsistency and readability fixes.

+ Added up-to-date README.md translation to Russian

---

README-fr.md
README-ru.md
README.ko-KR.md
README.md
README.zh-TW.md

parameter error

---

README-pl.md
README-ru.md
README.md
README.zh-CN.md
README.zh-TW.md

Fix translation on how to get window.document width/height

fix(docs): fix translation

---

README.md

There's an easy way to set multiple styles for an element.

Propose multiple style syntax

---

README.zh-CN.md

feat: update use chinese periods
